---
- hosts: all
  become: true
  tasks:
  - name: update ubuntu
    apt: sudo update
  - name: Install Docker
    apt: name=docker.io state=present
  - name: Start Docker Service
    command: sudo systemctl start docker
  - name: Deploy you application and run as container
    command: docker run -itd -p 8084:8081 swethamba859/insureme-app:1.0
